exibidor_id=tv_saguao
gestor_base_url=http://192.168.15.5:8080
device_ip=192.168.15.16
device_token=trocar-este-token
cache_dir=exibidor/cache
polling_segundos=5
heartbeat_segundos=10
display_command=fbi
